### ISSUE TITLE
restrict access issue

### ISSUE THREAD

**Issue by qodesmith** [qodesmith/artist-hub#1]
@bigtone1284

Not able to update albums belonging to user 1 when logged in as user one.

**Comment by qodesmith** [comment]
@h4w5 - Tony told me to tag you as well. I can give you more context on the situation if you end up getting to me before Tony does. Thanks bro.

**Comment by h4w5** [comment]
@qodesmith So I am not sure how strict they are being about issues, but the above issue makes no sense. Please format them as:

(The feature I'm working on; what I am trying to do)
(What my errors were, either error messages or what happened instead of assumed thing)
(Link to the relevant code or copy of the code)
(What I've tried to do to fix it)

For example, with the above, I'd say something like:

Hi!

I'm working on getting the user to be able to update their list of albums by clicking some button. They search an API for a list of albums, and then click on that album and it adds it to their list.

Instead there is no error logged, but the album does not show up on the albums list.

I put a `console.log` into the button click (it fires) and the connected model's event (it also fires). Don't know where to go from there. The ViewModel looks like:

```
view model code
```

The Model and Collection code look like:

```
model
collection
```

**Comment by qodesmith** [comment]
@h4w5 No problem. Solved this one on my own. Thanks.

**Comment by h4w5** [comment]
:)
